version: '3.8'
# primeira aplicação utilizando docker swarm ara um serviço web com Nginx e um banco de dados PostgreSQL.
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app_network

networks:
  app_network:
    driver: overlay

volumes:
  db_data:
